# SERVER
server.port=8080

# DATABASE
spring.datasource.url=jdbc:mysql://51.21.222.246:3306/chargequestdb
spring.datasource.username=satvik
spring.datasource.password=password123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=d36a47243485bddc79a5915f21e632eb4749acfc7338eaf08495a5663e67d274
jwt.expiration.time=86400000

# RAZORPAY
razorpay.key.id=rzp_test_S9Iag1mf2dDi1k
razorpay.key.secret=50yL0wCb3mHdMKpRQuYLuvcl